# Generated by Django 5.1.5 on 2025-01-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_cetegory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cetegory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cetegory_name',
            new_name='category_name',
        ),
    ]
