# Generated by Django 5.1.5 on 2025-01-28 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_rename_cetegory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Application.category'),
        ),
    ]
